### PR TITLE
Having more than 2 conditional expressions 

### PR DESCRIPTION
**Pull request by nremond**
Just starting the discussion.

I have a solution for defining the priorities of boolean operators - doing more testing and will push it on this branch.

cheers

### CODE REVIEW

**Comment by slandelle** [comment]
Wow! @pdalpra and I thought this was a lost cause... :)

**Comment by nremond** [comment]
This is a simple and working solution.

**Comment by slandelle** [comment]
You rock!

I'm afraid the next step will be boolean operations grouping...

**Comment by nremond** [comment]
Indeed, boolean grouping is the next step. 

Thinking about it ..,

**Pull request merged**
